basePath: /api
host: localhost:8080
info:
  contact: {}
  description: Kanban board with Golang, Postgres and JVT
  title: Kanban board
  version: "1.0"
paths:
  /:
    get:
      description: Returns a greeting message
      produces:
      - application/json
      responses:
        "200":
          description: Hello world
          schema:
            type: string
      summary: Hello World
swagger: "2.0"
